// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMBJj4FoIvFjHnDbkwHyzjX78JaDb7Zlc',
    appId: '1:721670076394:web:c11a44218902821f72a493',
    messagingSenderId: '721670076394',
    projectId: 'safety-app-b26f3',
    authDomain: 'safety-app-b26f3.firebaseapp.com',
    storageBucket: 'safety-app-b26f3.appspot.com',
    measurementId: 'G-XLTPEJZELF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDK_cRiFqyXHKiBUtOw7kG_87netjdS-k',
    appId: '1:721670076394:android:d40e3d3760e2d30872a493',
    messagingSenderId: '721670076394',
    projectId: 'safety-app-b26f3',
    storageBucket: 'safety-app-b26f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDToloCw4XRd7NgkELPeMnc6VjDrCszp2I',
    appId: '1:721670076394:ios:8473c7c7eeb9e62172a493',
    messagingSenderId: '721670076394',
    projectId: 'safety-app-b26f3',
    storageBucket: 'safety-app-b26f3.appspot.com',
    iosBundleId: 'com.example.weHeroes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDToloCw4XRd7NgkELPeMnc6VjDrCszp2I',
    appId: '1:721670076394:ios:8473c7c7eeb9e62172a493',
    messagingSenderId: '721670076394',
    projectId: 'safety-app-b26f3',
    storageBucket: 'safety-app-b26f3.appspot.com',
    iosBundleId: 'com.example.weHeroes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMBJj4FoIvFjHnDbkwHyzjX78JaDb7Zlc',
    appId: '1:721670076394:web:fe1584193ed82f4972a493',
    messagingSenderId: '721670076394',
    projectId: 'safety-app-b26f3',
    authDomain: 'safety-app-b26f3.firebaseapp.com',
    storageBucket: 'safety-app-b26f3.appspot.com',
    measurementId: 'G-SXP2JEVH4P',
  );
}
